{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmm.postgres.fullname" . }}
  labels:
    {{- include "dmm.postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "dmm.postgres.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    protocol: TCP
    port: {{ .Values.postgres.service.port }}
    targetPort: postgres
{{- end }}
